# https://github.com/ndmitchell/hlint
- extensions: [ { default: false } ]
- flags: [ { default: false } ]
- group: { name: dollar, enabled: true }
- group: { name: generalise, enabled: true }
- ignore: { name: Use <$> }
- modules:
  - default: false
  - { name: CMark }
  - { name: Conduit }
  - { name: Control.Exception }
  - { name: Control.Monad }
  - { name: Crypto.Hash.SHA1 }
  - { name: Data.Bool }
  - { name: Data.ByteString }
  - { name: Data.ByteString.Base64 }
  - { name: Data.ByteString.Builder }
  - { name: Data.ByteString.Lazy }
  - { name: Data.CaseInsensitive }
  - { name: Data.Char }
  - { name: Data.List }
  - { name: Data.List.NonEmpty }
  - { name: Data.Map }
  - { name: Data.Maybe }
  - { name: Data.Ord }
  - { name: Data.Set }
  - { name: Data.Text }
  - { name: Data.Text.Encoding }
  - { name: Data.Text.Encoding.Error }
  - { name: Data.Text.Lazy }
  - { name: Data.Text.Lazy.Encoding }
  - { name: Data.Time }
  - { name: Data.Traversable }
  - { name: Data.UUID }
  - { name: Data.Version }
  - { name: Data.XML.Types }
  - { name: Database.PostgreSQL.Simple }
  - { name: HaskellWeekly }
  - { name: HaskellWeekly.Application }
  - { name: HaskellWeekly.Episodes }
  - { name: HaskellWeekly.Handler.Advertising }
  - { name: HaskellWeekly.Handler.Base }
  - { name: HaskellWeekly.Handler.Episode }
  - { name: HaskellWeekly.Handler.Index }
  - { name: HaskellWeekly.Handler.Issue }
  - { name: HaskellWeekly.Handler.Newsletter }
  - { name: HaskellWeekly.Handler.NewsletterFeed }
  - { name: HaskellWeekly.Handler.Podcast }
  - { name: HaskellWeekly.Handler.PodcastFeed }
  - { name: HaskellWeekly.Handler.Redirect }
  - { name: HaskellWeekly.Handler.Static }
  - { name: HaskellWeekly.Issues }
  - { name: HaskellWeekly.Main }
  - { name: HaskellWeekly.Middleware }
  - { name: HaskellWeekly.Server }
  - { name: HaskellWeekly.Template.Advertising }
  - { name: HaskellWeekly.Template.Base }
  - { name: HaskellWeekly.Template.Episode }
  - { name: HaskellWeekly.Template.Index }
  - { name: HaskellWeekly.Template.Issue }
  - { name: HaskellWeekly.Template.Newsletter }
  - { name: HaskellWeekly.Template.NewsletterFeed }
  - { name: HaskellWeekly.Template.Podcast }
  - { name: HaskellWeekly.Template.PodcastFeed }
  - { name: HaskellWeekly.Type.Article }
  - { name: HaskellWeekly.Type.Articles }
  - { name: HaskellWeekly.Type.Audio }
  - { name: HaskellWeekly.Type.Caption }
  - { name: HaskellWeekly.Type.Config }
  - { name: HaskellWeekly.Type.Content }
  - { name: HaskellWeekly.Type.Date }
  - { name: HaskellWeekly.Type.Duration }
  - { name: HaskellWeekly.Type.Episode }
  - { name: HaskellWeekly.Type.Guid }
  - { name: HaskellWeekly.Type.Issue }
  - { name: HaskellWeekly.Type.Number }
  - { name: HaskellWeekly.Type.Redirect }
  - { name: HaskellWeekly.Type.Route }
  - { name: HaskellWeekly.Type.Size }
  - { name: HaskellWeekly.Type.State }
  - { name: HaskellWeekly.Type.Summary }
  - { name: HaskellWeekly.Type.Title }
  - { name: Lucid }
  - { name: Lucid.Base }
  - { name: Network.HTTP.Types }
  - { name: Network.HTTP.Types.Header }
  - { name: Network.URI }
  - { name: Network.Wai }
  - { name: Network.Wai.Handler.Warp }
  - { name: Network.Wai.Internal }
  - { name: Network.Wai.Middleware.ForceSSL }
  - { name: Network.Wai.Middleware.Gzip }
  - { name: Numeric.Natural }
  - { name: Paths_haskellweekly }
  - { name: System.Environment }
  - { name: System.FilePath }
  - { name: System.IO }
  - { name: System.IO.Error }
  - { name: Text.Atom.Feed }
  - { name: Text.Feed.Constructor }
  - { name: Text.Feed.Export }
  - { name: Text.Feed.Types }
  - { name: Text.ParserCombinators.ReadP }
  - { name: Text.Printf }
  - { name: Text.Read }
  - { name: Text.RSS.Syntax }
  - { name: Text.XML.Unresolved }
