on:
  pull_request:
    branches:
      - haskellweekly
  push:
    branches:
      - haskellweekly
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - id: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: 8.10.2
          cabal-version: 3.4.0.0
      - run: cabal freeze
      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ hashFiles('cabal.project.freeze') }}
      - run: cabal test --test-show-details direct
      - run: cabal install --installdir docker --install-method copy
      - uses: actions/upload-artifact@v2
        with:
          path: docker/haskellweekly
          name: haskellweekly-${{ github.sha }}
      # - run: cabal check
      # - run: cabal sdist --output-dir .
      # - uses: actions/upload-artifact@v2
      #   with:
      #     path: haskellweekly-*.tar.gz
      #     name: haskellweekly-${{ github.sha }}.tar.gz
      # - uses: docker/setup-buildx-action@v1
      # - uses: docker/login-action@v1
      #   with:
      #     registry: docker.pkg.github.com
      #     username: ${{ github.repository_owner }}
      #     password: ${{ github.token }}
      # - uses: docker/build-push-action@v2
      #   with:
      #     context: docker
      #     file: docker/Dockerfile
      #     push: true
      #     tags: docker.pkg.github.com/${{ github.repository }}/haskellweekly:${{ github.sha }}
