on:
  pull_request:
    branches:
      - haskellweekly
  push:
    branches:
      - haskellweekly
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - id: haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: 8.10.2
          cabal-version: 3.4.0.0
      - run: cabal freeze
      - uses: actions/cache@v2
        with:
          path: ${{ steps.haskell.outputs.cabal-store }}
          key: ${{ hashFiles('cabal.project.freeze') }}
      - run: cabal test --test-show-details direct
      - run: cabal install --installdir docker --install-method copy
      - uses: actions/upload-artifact@v2
        with:
          path: docker/haskellweekly
          name: haskellweekly-${{ github.sha }}
      - run: cabal check
      - run: cabal sdist --output-dir .
      - uses: actions/upload-artifact@v2
        with:
          path: haskellweekly-*.tar.gz
          name: haskellweekly-${{ github.sha }}.tar.gz
      - uses: docker/setup-buildx-action@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - id: ecr
        uses: aws-actions/amazon-ecr-login@v1
      - run: cp --recursive data docker
      - uses: docker/build-push-action@v2
        with:
          context: docker
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.ecr.outputs.registry }}/haskellweekly:${{ github.sha }}
